name: Publish MODIUM payload to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "mods_payload/**"
      - ".github/workflows/publish-pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build public site with payload
        run: |
          mkdir -p public
          test -d mods_payload || { echo "mods_payload/ not found"; exit 1; }

          # Crée le ZIP au bon endroit (public)
          (cd mods_payload && zip -r ../public/mods_payload.zip .)

          # Manifest SHA1 (optionnel, utile pour diagnostiquer)
          (cd mods_payload && sha1sum *.jar 2>/dev/null || true) > public/mods_manifest.sha1

          # Petite page d'index (optionnelle)
          cat > public/index.html << 'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>MODIUM Payload</title>
          <h1>MODIUM Payload</h1>
          <p><a href="mods_payload.zip">Download mods_payload.zip</a></p>
          <p><a href="mods_manifest.sha1">mods_manifest.sha1</a></p>
          HTML

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
